API_KEY = ':)'

IMAGES_FOR_QUOTES = [
    'images/1.jpg',
    'images/2.jpg',
    'images/3.jpg',
    'images/4.jpg',
    'images/5.jpeg',
    'images/6.jpg',
    'images/7.jpg',
    'images/8.jpg',
    'images/9.jpg',
    'images/11.jpg',
    'images/12.jpg',
    'images/13.jpg',
    'images/14.jpg',
    'images/15.jpg',
    'images/16.jpg',
    'images/17.jpg',
    'images/19.jpg',
    'images/20.jpg',
    'images/21.jpg',
    'images/22.jpg',
    'images/23.jpg',
    'images/24.jpg',
    'images/25.jpg',
    'images/26.jpg',
    'images/27.jpg',
]

FONTS_FOR_QUOTES = [
    'fonts/1.otf',
    'fonts/2.ttf',
    'fonts/3.ttf',
    'fonts/4.ttf',
    'fonts/5.ttf',
    'fonts/6.otf',
    'fonts/7.ttf',
    'fonts/8.ttf',
    'fonts/9.otf',
    'fonts/10.ttf',
    'fonts/11.ttf',
    'fonts/12.ttf',
    'fonts/13.ttf',
]